#
# Vivado (TM) v2016.1 (64-bit)
#
# ReconosTemplate.tcl: Tcl script for re-creating project 'ReconosTemplate'
#
# Generated by Vivado on Thu Feb 16 16:29:00 +0100 2017
# IP Build 1537824 on Fri Apr  8 04:28:57 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (ReconosTemplate.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "ReconosTemplate.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}


# Set the directory where the IP integrator cores live
set reconos_ip_dir "/home/meise/git/reconos_zynq/reconos/demos/sort_demo_vivado/build.hw/pcores"

# How many hardware threads do you want?
set num_hwts 2

set proj_name ""
set proj_path ""

# Parse command line arguments
if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "-proj_name" { incr i; set proj_name  [lindex $::argv $i] }
      "-proj_path" { incr i; set proj_path [lindex $::argv $i] }
      "-help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}





proc reconos_setup_hw {new_project_name new_project_path reconos_ip_dir num_hwts} {
    # Set the directory path for the original project from where this script was exported
    #set orig_proj_dir "[file normalize "$origin_dir/ReconosTemplate"]"

    # Create project
    if { [llength $new_project_name] > 0} {
        create_project -force $new_project_name $new_project_path -part xc7z020clg484-1
    }

    # Get the directory path for the current project
    #set proj_dir [get_property directory [current_project]]

    # Reconstruct message rules
    # None

    # Set project properties
    #set obj [get_projects ReconosTemplate]
    # Set the directory where the new project will be created
    set proj_name [current_project]
    set proj_dir [get_property directory [current_project]]
    
    set_property "board_part" "em.avnet.com:zed:part0:1.3" $proj_name
    set_property "default_lib" "xil_defaultlib" $proj_name
    set_property "sim.ip.auto_export_scripts" "1" $proj_name
    set_property "simulator_language" "Mixed" $proj_name
    set_property "target_language" "VHDL" $proj_name

    # Create 'sources_1' fileset (if not found)
    if {[string equal [get_filesets -quiet sources_1] ""]} {
    create_fileset -srcset sources_1
    }

    # Set 'sources_1' fileset object
    set obj [get_filesets sources_1]
    # Empty (no sources present)

    # Set 'sources_1' fileset properties
    set obj [get_filesets sources_1]

    # Create 'constrs_1' fileset (if not found)
    if {[string equal [get_filesets -quiet constrs_1] ""]} {
    create_fileset -constrset constrs_1
    }

    # Set 'constrs_1' fileset object
    set obj [get_filesets constrs_1]

    # Empty (no sources present)

    # Set 'constrs_1' fileset properties
    set obj [get_filesets constrs_1]

    # Create 'sim_1' fileset (if not found)
    if {[string equal [get_filesets -quiet sim_1] ""]} {
    create_fileset -simset sim_1
    }

    # Set 'sim_1' fileset object
    set obj [get_filesets sim_1]
    # Empty (no sources present)

    # Set 'sim_1' fileset properties
    set obj [get_filesets sim_1]
    set_property "transport_int_delay" "0" $obj
    set_property "transport_path_delay" "0" $obj
    set_property "xelab.nosort" "1" $obj
    set_property "xelab.unifast" "" $obj

    # Create 'synth_1' run (if not found)
    if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z020clg484-1 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
    } else {
    set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
    set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
    }
    set obj [get_runs synth_1]

    # set the current synth run
    current_run -synthesis [get_runs synth_1]

    # Create 'impl_1' run (if not found)
    if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z020clg484-1 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
    } else {
    set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
    set_property flow "Vivado Implementation 2016" [get_runs impl_1]
    }
    set obj [get_runs impl_1]
    set_property "steps.write_bitstream.args.readback_file" "0" $obj
    set_property "steps.write_bitstream.args.verbose" "0" $obj

    # set the current impl run
    current_run -implementation [get_runs impl_1]

    #
    # Start block design
    #
    create_bd_design "design_1"
    update_compile_order -fileset sources_1

    # Add reconos repository
    set_property  ip_repo_paths  $reconos_ip_dir [current_project]
    update_ip_catalog

	
    # Add system reset module
    create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 reset_0

    # Add processing system for Zynq Board
    create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddrx_rtl:1.0 DDR
    create_bd_intf_port -mode Master -vlnv xilinx.com:display_processing_system7:fixedio_rtl:1.0 FIXED_IO
    create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 processing_system7_0
    # Connect DDR and fixed IO
    connect_bd_intf_net -intf_net processing_system7_0_DDR [get_bd_intf_ports DDR] [get_bd_intf_pins processing_system7_0/DDR]
    connect_bd_intf_net -intf_net processing_system7_0_FIXED_IO [get_bd_intf_ports FIXED_IO] [get_bd_intf_pins processing_system7_0/FIXED_IO]
    # Make sure required AXI ports are active
    set_property -dict [list CONFIG.PCW_USE_M_AXI_GP0 {1} CONFIG.PCW_USE_S_AXI_ACP {1}] [get_bd_cells processing_system7_0]
    # Add interrupt port 
    set_property -dict [list CONFIG.PCW_USE_FABRIC_INTERRUPT {1} CONFIG.PCW_IRQ_F2P_INTR {1}] [get_bd_cells processing_system7_0]
    # Set Frequencies
    set_property -dict [ list CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {100} ] [get_bd_cells processing_system7_0]
    # Tie AxUSER signals on ACP port to '1' to enable cache coherancy
    set_property -dict [list CONFIG.PCW_USE_DEFAULT_ACP_USER_VAL {1}] [get_bd_cells processing_system7_0]

    # Add AXI Busses and set properties
    create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_mem
    create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_hwt
    set_property -dict [ list CONFIG.NUM_MI {1}  ] [get_bd_cells axi_mem]
    set_property -dict [ list CONFIG.NUM_MI {5}  ] [get_bd_cells axi_hwt]

    # Add reconos stuff
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_clock:1.0 reconos_clock_0
    # Bugfix: literal for C_CLKIN_PERIOD has to be a real literal, e.g. needs to include the decimal point
    set_property -dict [list CONFIG.C_CLKIN_PERIOD {10.0}] [get_bd_cells reconos_clock_0]
    #create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_fifo_async:1.0 reconos_fifo_async_0
    #create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_hwt_idle:1.0 reconos_hwt_idle_0
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_memif_arbiter:1.0 reconos_memif_arbiter_0
    set_property -dict [list CONFIG.C_NUM_HWTS $num_hwts ] [get_bd_cells reconos_memif_arbiter_0]
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_memif_memory_controller:1.0 reconos_memif_memory_controller_0
    #create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_memif_mmu_microblaze:1.0 reconos_memif_mmu_microblaze_0
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_memif_mmu_zynq:1.0 reconos_memif_mmu_zynq_0
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_osif_intc:1.0 reconos_osif_intc_0
    set_property -dict [list CONFIG.C_NUM_INTERRUPTS $num_hwts ] [get_bd_cells reconos_osif_intc_0]
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_osif:1.0 reconos_osif_0
    set_property -dict [list CONFIG.C_NUM_HWTS  $num_hwts ] [get_bd_cells reconos_osif_0]
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_proc_control:1.0 reconos_proc_control_0
    set_property -dict [list CONFIG.C_NUM_HWTS  $num_hwts ] [get_bd_cells reconos_proc_control_0]
    create_bd_cell -type ip -vlnv upb.ceg:reconos:timer:1.0 timer_0

    # Add hardware thread
    create_bd_cell -type ip -vlnv upb.ceg:reconos:rt_sortdemo:1.0 rt_sortdemo_0
    create_bd_cell -type ip -vlnv upb.ceg:reconos:rt_sortdemo:1.0 rt_sortdemo_1

    # Add FIFOS between hardware threads and arbiter
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_fifo_sync:1.0 reconos_fifo_osif_hw2sw_0
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_fifo_sync:1.0 reconos_fifo_osif_sw2hw_0
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_fifo_sync:1.0 reconos_fifo_memif_hwt2mem_0
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_fifo_sync:1.0 reconos_fifo_memif_mem2hwt_0
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_fifo_sync:1.0 reconos_fifo_osif_hw2sw_1
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_fifo_sync:1.0 reconos_fifo_osif_sw2hw_1
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_fifo_sync:1.0 reconos_fifo_memif_hwt2mem_1
    create_bd_cell -type ip -vlnv upb.ceg:reconos:reconos_fifo_sync:1.0 reconos_fifo_memif_mem2hwt_1

    # Set sizes of FIFOs
    set_property -dict [list CONFIG.C_FIFO_ADDR_WIDTH {3}] [get_bd_cells reconos_fifo_osif_hw2sw_0]
    set_property -dict [list CONFIG.C_FIFO_ADDR_WIDTH {3}] [get_bd_cells reconos_fifo_osif_sw2hw_0]
    set_property -dict [list CONFIG.C_FIFO_ADDR_WIDTH {3}] [get_bd_cells reconos_fifo_osif_hw2sw_1]
    set_property -dict [list CONFIG.C_FIFO_ADDR_WIDTH {3}] [get_bd_cells reconos_fifo_osif_sw2hw_1]

    set_property -dict [list CONFIG.C_FIFO_ADDR_WIDTH {7}] [get_bd_cells reconos_fifo_memif_hwt2mem_0]
    set_property -dict [list CONFIG.C_FIFO_ADDR_WIDTH {7}] [get_bd_cells reconos_fifo_memif_mem2hwt_0]
    set_property -dict [list CONFIG.C_FIFO_ADDR_WIDTH {7}] [get_bd_cells reconos_fifo_memif_hwt2mem_1]
    set_property -dict [list CONFIG.C_FIFO_ADDR_WIDTH {7}] [get_bd_cells reconos_fifo_memif_mem2hwt_1]

    #
    # Connections between components
    #

    # AXI
    connect_bd_intf_net -intf_net reconos_memif_memory_controller_0_M_AXI [get_bd_intf_pins reconos_memif_memory_controller_0/M_AXI] [get_bd_intf_pins axi_mem/S00_AXI]
    connect_bd_intf_net -intf_net reconos_memif_memory_controller_0_S_AXI [get_bd_intf_pins processing_system7_0/S_AXI_ACP] [get_bd_intf_pins axi_mem/M00_AXI]

    connect_bd_intf_net -intf_net axi_hwt_S00_AXI [get_bd_intf_pins axi_hwt/S00_AXI] [get_bd_intf_pins processing_system7_0/M_AXI_GP0] 
    connect_bd_intf_net -intf_net axi_hwt_M00_AXI [get_bd_intf_pins axi_hwt/M00_AXI] [get_bd_intf_pins reconos_clock_0/S_AXI] 
    connect_bd_intf_net -intf_net axi_hwt_M01_AXI [get_bd_intf_pins axi_hwt/M01_AXI] [get_bd_intf_pins reconos_osif_intc_0/S_AXI]
    connect_bd_intf_net -intf_net axi_hwt_M02_AXI [get_bd_intf_pins axi_hwt/M02_AXI] [get_bd_intf_pins reconos_osif_0/S_AXI]
    connect_bd_intf_net -intf_net axi_hwt_M03_AXI [get_bd_intf_pins axi_hwt/M03_AXI] [get_bd_intf_pins reconos_proc_control_0/S_AXI]
    connect_bd_intf_net -intf_net axi_hwt_M04_AXI [get_bd_intf_pins axi_hwt/M04_AXI] [get_bd_intf_pins timer_0/S_AXI]

    # Memory controller
    connect_bd_intf_net [get_bd_intf_pins reconos_memif_memory_controller_0/MEMIF_Hwt2Mem_In] [get_bd_intf_pins reconos_memif_mmu_zynq_0/MEMIF_Hwt2Mem_Out]
    connect_bd_intf_net [get_bd_intf_pins reconos_memif_memory_controller_0/MEMIF_Mem2Hwt_In] [get_bd_intf_pins reconos_memif_mmu_zynq_0/MEMIF_Mem2Hwt_Out]

    # MMU
    connect_bd_intf_net [get_bd_intf_pins reconos_memif_mmu_zynq_0/MEMIF_Hwt2Mem_In] [get_bd_intf_pins reconos_memif_arbiter_0/MEMIF_Hwt2Mem_OUT]
    connect_bd_intf_net [get_bd_intf_pins reconos_memif_mmu_zynq_0/MEMIF_Mem2Hwt_In] [get_bd_intf_pins reconos_memif_arbiter_0/MEMIF_Mem2Hwt_Out]
    connect_bd_net [get_bd_pins reconos_memif_mmu_zynq_0/MMU_Pgf] [get_bd_pins reconos_proc_control_0/MMU_Pgf]
    connect_bd_net [get_bd_pins reconos_memif_mmu_zynq_0/MMU_Retry] [get_bd_pins reconos_proc_control_0/MMU_Retry]
    connect_bd_net [get_bd_pins reconos_memif_mmu_zynq_0/MMU_Pgd] [get_bd_pins reconos_proc_control_0/MMU_Pgd]
    connect_bd_net [get_bd_pins reconos_memif_mmu_zynq_0/MMU_Fault_Addr] [get_bd_pins reconos_proc_control_0/MMU_Fault_Addr]
    set_property -dict [list CONFIG.C_TLB_SIZE {16}] [get_bd_cells reconos_memif_mmu_zynq_0]

    # OSIF <-> FIFOs <-> HWT
    connect_bd_intf_net [get_bd_intf_pins rt_sortdemo_0/OSIF_Hw2SW] [get_bd_intf_pins reconos_fifo_osif_hw2sw_0/FIFO_M]
    connect_bd_intf_net [get_bd_intf_pins rt_sortdemo_0/OSIF_Sw2Hw] [get_bd_intf_pins reconos_fifo_osif_sw2hw_0/FIFO_S]
    connect_bd_intf_net [get_bd_intf_pins reconos_fifo_osif_hw2sw_0/FIFO_S] [get_bd_intf_pins reconos_osif_0/OSIF_hw2sw_0]
    connect_bd_intf_net [get_bd_intf_pins reconos_fifo_osif_sw2hw_0/FIFO_M] [get_bd_intf_pins reconos_osif_0/OSIF_sw2hw_0]
    connect_bd_net [get_bd_pins reconos_fifo_osif_hw2sw_0/FIFO_Has_Data] [get_bd_pins reconos_osif_intc_0/OSIF_INTC_In_0]

    connect_bd_intf_net [get_bd_intf_pins rt_sortdemo_1/OSIF_Hw2SW] [get_bd_intf_pins reconos_fifo_osif_hw2sw_1/FIFO_M]
    connect_bd_intf_net [get_bd_intf_pins rt_sortdemo_1/OSIF_Sw2Hw] [get_bd_intf_pins reconos_fifo_osif_sw2hw_1/FIFO_S]
    connect_bd_intf_net [get_bd_intf_pins reconos_fifo_osif_hw2sw_1/FIFO_S] [get_bd_intf_pins reconos_osif_0/OSIF_hw2sw_1]
    connect_bd_intf_net [get_bd_intf_pins reconos_fifo_osif_sw2hw_1/FIFO_M] [get_bd_intf_pins reconos_osif_0/OSIF_sw2hw_1]
    connect_bd_net [get_bd_pins reconos_fifo_osif_hw2sw_1/FIFO_Has_Data] [get_bd_pins reconos_osif_intc_0/OSIF_INTC_In_1]

    # Arbiter <-> FIFOs <-> HWT
    connect_bd_intf_net [get_bd_intf_pins rt_sortdemo_0/MEMIF_Hwt2Mem] [get_bd_intf_pins reconos_fifo_memif_hwt2mem_0/FIFO_M]
    connect_bd_intf_net [get_bd_intf_pins rt_sortdemo_0/MEMIF_Mem2Hwt] [get_bd_intf_pins reconos_fifo_memif_mem2hwt_0/FIFO_S]
    connect_bd_intf_net [get_bd_intf_pins reconos_memif_arbiter_0/MEMIF_Hwt2Mem_0] [get_bd_intf_pins reconos_fifo_memif_hwt2mem_0/FIFO_S]
    connect_bd_intf_net [get_bd_intf_pins reconos_memif_arbiter_0/MEMIF_Mem2Hwt_0] [get_bd_intf_pins reconos_fifo_memif_mem2hwt_0/FIFO_M]

    connect_bd_intf_net [get_bd_intf_pins rt_sortdemo_1/MEMIF_Hwt2Mem] [get_bd_intf_pins reconos_fifo_memif_hwt2mem_1/FIFO_M]
    connect_bd_intf_net [get_bd_intf_pins rt_sortdemo_1/MEMIF_Mem2Hwt] [get_bd_intf_pins reconos_fifo_memif_mem2hwt_1/FIFO_S]
    connect_bd_intf_net [get_bd_intf_pins reconos_memif_arbiter_0/MEMIF_Hwt2Mem_1] [get_bd_intf_pins reconos_fifo_memif_hwt2mem_1/FIFO_S]
    connect_bd_intf_net [get_bd_intf_pins reconos_memif_arbiter_0/MEMIF_Mem2Hwt_1] [get_bd_intf_pins reconos_fifo_memif_mem2hwt_1/FIFO_M]

    #
    # Connect clocks - most clock inputs come from the reconos_clock module
    #

    connect_bd_net [get_bd_pins processing_system7_0/FCLK_CLK0] [get_bd_pins reconos_clock_0/CLK_Ref]

    #connect_bd_net [get_bd_pins processing_system7_0/FCLK_CLK0] [get_bd_pins axi_hwt/S00_ACLK]

    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Out] \
                            [get_bd_pins processing_system7_0/M_AXI_GP0_ACLK] \
                            [get_bd_pins processing_system7_0/S_AXI_ACP_ACLK] \
                            [get_bd_pins reconos_clock_0/S_AXI_ACLK] \
                            [get_bd_pins reconos_memif_memory_controller_0/M_AXI_ACLK] \
                            [get_bd_pins axi_mem/ACLK] \
                            [get_bd_pins axi_mem/M00_ACLK] \
                            [get_bd_pins axi_mem/S00_ACLK] \
                            [get_bd_pins axi_hwt/ACLK] \
                            [get_bd_pins axi_hwt/M00_ACLK] \
                            [get_bd_pins axi_hwt/M01_ACLK] \
                            [get_bd_pins axi_hwt/M02_ACLK] \
                            [get_bd_pins axi_hwt/M03_ACLK] \
                            [get_bd_pins axi_hwt/M04_ACLK] \
                            [get_bd_pins axi_hwt/S00_ACLK] \
                            [get_bd_pins reconos_osif_0/S_AXI_ACLK] [get_bd_pins reconos_osif_intc_0/S_AXI_ACLK] \
                            [get_bd_pins reconos_proc_control_0/S_AXI_ACLK] \
                            [get_bd_pins reset_0/slowest_sync_clk] \
                            [get_bd_pins timer_0/S_AXI_ACLK]
                            
                            
    # MEMIF Components
    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Out] [get_bd_pins reconos_memif_mmu_zynq_0/SYS_Clk]
    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Out] [get_bd_pins reconos_memif_arbiter_0/SYS_Clk]

    # FIFOs
    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Out] [get_bd_pins reconos_fifo_osif_hw2sw_0/FIFO_Clk]
    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Out] [get_bd_pins reconos_fifo_osif_sw2hw_0/FIFO_Clk]
    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Out] [get_bd_pins reconos_fifo_osif_hw2sw_1/FIFO_Clk]
    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Out] [get_bd_pins reconos_fifo_osif_sw2hw_1/FIFO_Clk]

    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Out] [get_bd_pins reconos_fifo_memif_hwt2mem_0/FIFO_Clk]
    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Out] [get_bd_pins reconos_fifo_memif_mem2hwt_0/FIFO_Clk]
    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Out] [get_bd_pins reconos_fifo_memif_hwt2mem_1/FIFO_Clk]
    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Out] [get_bd_pins reconos_fifo_memif_mem2hwt_1/FIFO_Clk]

    # HWTs
    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Out] [get_bd_pins rt_sortdemo_0/HWT_Clk]
    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Out] [get_bd_pins rt_sortdemo_1/HWT_Clk]


    #
    # Connect Resets
    #
    connect_bd_net [get_bd_pins reconos_clock_0/CLK0_Locked] [get_bd_pins reset_0/DCM_Locked] 

    connect_bd_net [get_bd_pins reset_0/ext_reset_in] [get_bd_pins processing_system7_0/FCLK_RESET0_N] 
    connect_bd_net [get_bd_pins reset_0/Interconnect_aresetn] \
                            [get_bd_pins axi_mem/ARESETN] \
                            [get_bd_pins axi_mem/M00_ARESETN] \
                            [get_bd_pins axi_mem/S00_ARESETN] \
                            [get_bd_pins axi_hwt/ARESETN] \
                            [get_bd_pins axi_hwt/M00_ARESETN] \
                            [get_bd_pins axi_hwt/M01_ARESETN] \
                            [get_bd_pins axi_hwt/M02_ARESETN] \
                            [get_bd_pins axi_hwt/M03_ARESETN] \
                            [get_bd_pins axi_hwt/M04_ARESETN] \
                            [get_bd_pins axi_hwt/S00_ARESETN]
    # Proc_control resets
    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Hwt_Rst_0] [get_bd_pins rt_sortdemo_0/HWT_Rst]
    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Hwt_Rst_0] [get_bd_pins reconos_fifo_memif_mem2hwt_0/FIFO_Rst]
    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Hwt_Rst_0] [get_bd_pins reconos_fifo_memif_hwt2mem_0/FIFO_Rst]
    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Hwt_Rst_0] [get_bd_pins reconos_fifo_osif_hw2sw_0/FIFO_Rst]
    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Hwt_Rst_0] [get_bd_pins reconos_fifo_osif_sw2hw_0/FIFO_Rst]
    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Hwt_Signal_0] [get_bd_pins rt_sortdemo_0/HWT_Signal]

    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Hwt_Rst_1] [get_bd_pins rt_sortdemo_1/HWT_Rst]
    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Hwt_Rst_1] [get_bd_pins reconos_fifo_memif_mem2hwt_1/FIFO_Rst]
    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Hwt_Rst_1] [get_bd_pins reconos_fifo_memif_hwt2mem_1/FIFO_Rst]
    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Hwt_Rst_1] [get_bd_pins reconos_fifo_osif_hw2sw_1/FIFO_Rst]
    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Hwt_Rst_1] [get_bd_pins reconos_fifo_osif_sw2hw_1/FIFO_Rst]
    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Hwt_Signal_1] [get_bd_pins rt_sortdemo_1/HWT_Signal]

    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Sys_Rst] [get_bd_pins reconos_memif_arbiter_0/SYS_Rst]
    connect_bd_net [get_bd_pins reconos_memif_mmu_zynq_0/SYS_Rst] [get_bd_pins reconos_proc_control_0/PROC_Sys_Rst]

    # ReconoOS Peripherals reset by peripheral_aresetn
    connect_bd_net [get_bd_pins reset_0/peripheral_aresetn] [get_bd_pins reconos_clock_0/S_AXI_ARESETN]
    connect_bd_net [get_bd_pins reset_0/peripheral_aresetn] [get_bd_pins timer_0/S_AXI_ARESETN]
    connect_bd_net [get_bd_pins reset_0/peripheral_aresetn] [get_bd_pins reconos_proc_control_0/S_AXI_ARESETN]
    connect_bd_net [get_bd_pins reset_0/peripheral_aresetn] [get_bd_pins reconos_osif_intc_0/S_AXI_ARESETN]
    connect_bd_net [get_bd_pins reset_0/peripheral_aresetn] [get_bd_pins reconos_osif_0/S_AXI_ARESETN]
    connect_bd_net [get_bd_pins reset_0/peripheral_aresetn] [get_bd_pins reconos_memif_memory_controller_0/M_AXI_ARESETN]

    #
    # Connect interrupts
    #
    create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 xlconstant_0
    set_property -dict [list CONFIG.CONST_VAL {0}] [get_bd_cells xlconstant_0]
    
    create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat:2.1 xlconcat_0
    set_property -dict [list CONFIG.NUM_PORTS {16}] [get_bd_cells xlconcat_0]
    
    # This is needed to shift the interrupt lines to the right positions
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In0]
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In1]
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In2]
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In3]
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In4]
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In5]
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In6]
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In7]
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In8]
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In9]
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In10]
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In11]
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In12]
    connect_bd_net [get_bd_pins xlconstant_0/dout] [get_bd_pins xlconcat_0/In13]
    
    connect_bd_net [get_bd_pins reconos_osif_intc_0/OSIF_INTC_Out] [get_bd_pins xlconcat_0/In14]
    connect_bd_net [get_bd_pins reconos_proc_control_0/PROC_Pgf_Int] [get_bd_pins xlconcat_0/In15]
    connect_bd_net [get_bd_pins xlconcat_0/dout] [get_bd_pins processing_system7_0/IRQ_F2P]


    #
    # Memory Map of peripheperals
    #

    set_property -dict [list CONFIG.C_BASEADDR {0x6fe00000} CONFIG.C_HIGHADDR {0x6fe0ffff}] [get_bd_cells reconos_proc_control_0]
    set_property -dict [list CONFIG.C_BASEADDR {0x75a00000} CONFIG.C_HIGHADDR {0x75a0ffff}] [get_bd_cells reconos_osif_0]
    set_property -dict [list CONFIG.C_BASEADDR {0x64a00000} CONFIG.C_HIGHADDR {0x64a0ffff}] [get_bd_cells timer_0]
    set_property -dict [list CONFIG.C_BASEADDR {0x7b400000} CONFIG.C_HIGHADDR {0x7b40ffff}] [get_bd_cells reconos_osif_intc_0]
    set_property -dict [list CONFIG.C_BASEADDR {0x69e00000} CONFIG.C_HIGHADDR {0x69e0ffff}] [get_bd_cells reconos_clock_0]
    
    create_bd_addr_seg -range 64K -offset 0x6FE00000 [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs {reconos_proc_control_0/S_AXI/reg0 }] SEG1
    create_bd_addr_seg -range 64K -offset 0x75a00000 [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs {reconos_osif_0/S_AXI/reg0 }] SEG2
    create_bd_addr_seg -range 64K -offset 0x64a00000 [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs {timer_0/S_AXI/reg0 }] SEG3
    create_bd_addr_seg -range 64K -offset 0x7b400000 [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs {reconos_osif_intc_0/S_AXI/reg0 }] SEG4
    create_bd_addr_seg -range 64K -offset 0x69e00000 [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs {reconos_clock_0/S_AXI/reg0 }] SEG5

    assign_bd_address [get_bd_addr_segs {processing_system7_0/S_AXI_ACP/ACP_DDR_LOWOCM }]
    assign_bd_address [get_bd_addr_segs {processing_system7_0/S_AXI_ACP/ACP_M_AXI_GP0 }]

    
                            
    # Update layout of block design
    regenerate_bd_layout

    #make wrapper file; vivado needs it to implement design
    make_wrapper -files [get_files $proj_dir/$proj_name.srcs/sources_1/bd/design_1/design_1.bd] -top
    add_files -norecurse $proj_dir/$proj_name.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
    update_compile_order -fileset sources_1
    update_compile_order -fileset sim_1
    #set_property top "$proj_dir/$proj_name.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd" [current_fileset]
    set_property top design_1_wrapper [current_fileset]
    save_bd_design
}


 
proc reconos_built_bitstream {} {
    # create bitstream
    launch_runs impl_1 -to_step write_bitstream -jobs 2
}

reconos_setup_hw $proj_name $proj_path $reconos_ip_dir $num_hwts



puts "INFO: Project created:ReconosTemplate"

#
# Generate Block Design
#

#update_compile_order -fileset sources_1
#generate_target all [get_files  C:/Users/meise/Vivado/ReconosTemplate/ReconosTemplate.srcs/sources_1/bd/design_1/design_1.bd]
#export_ip_user_files -of_objects [get_files C:/Users/meise/Vivado/ReconosTemplate/ReconosTemplate.srcs/sources_1/bd/design_1/design_1.bd] -no_script -force -quiet
#export_simulation -of_objects [get_files C:/Users/meise/Vivado/ReconosTemplate/ReconosTemplate.srcs/sources_1/bd/design_1/design_1.bd] -directory C:/Users/meise/Vivado/ReconosTemplate/ReconosTemplate.ip_user_files/sim_scripts -ip_user_files_dir C:/Users/meise/Vivado/ReconosTemplate/ReconosTemplate.ip_user_files -ipstatic_source_dir C:/Users/meise/Vivado/ReconosTemplate/ReconosTemplate.ip_user_files/ipstatic -force -quiet


#source C:/Users/meise/Vivado/ReconosTemplate.tcl
#source /home/meise/git/reconos_zynq/reconos/tools/tcl/ReconosTemplate.tcl